const EpisodeActionTypes = {
	FETCH_EPISODES_START: 'FETCH_EPISODES_START',
	FETCH_EPISODES_SUCCESS: 'FETCH_EPISODES_SUCCESS',
	FETCH_EPISODES_FAIL: 'FETCH_EPISODES_FAIL'
};

export default EpisodeActionTypes;
