const HomeActionTypes = {
	FETCH_HOME_DATA_START: 'FETCH_HOME_DATA_START',
	FETCH_HOME_DATA_SUCCESS: 'FETCH_HOME_DATA_SUCCESS',
	FETCH_HOME_DATA_FAIL: 'FETCH_HOME_DATA_FAIL'
};

export default HomeActionTypes;
