const AuthActionTypes = {
	USER_AUTH_VERIFICATION_START: 'USER_AUTH_VERIFICATION_START',
	USER_AUTH_VERIFICATION_SUCCESS: 'USER_AUTH_VERIFICATION_SUCCESS',
	USER_AUTH_VERIFICATION_FAIL: 'USER_AUTH_VERIFICATION_FAIL'
};

export default AuthActionTypes;
