const EpisodeCatalogActionTypes = {
	FETCH_EPISODE_CATALOG_START: 'FETCH_EPISODE_CATALOG_START',
	FETCH_EPISODE_CATALOG_SUCCESS: 'FETCH_EPISODE_CATALOG_SUCCESS',
	FETCH_EPISODE_CATALOG_FAIL: 'FETCH_EPISODE_CATALOG_FAIL'
};

export default EpisodeCatalogActionTypes;
